apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.imageSeatAdjusterApp.name}}
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "{{.Values.imageSeatAdjusterApp.daprAppid}}"
    dapr.io/app-port: "{{.Values.imageSeatAdjusterApp.daprPort}}"
    dapr.io/log-level: "debug"
    dapr.io/config: "config.yaml"
  labels:
    {{- include "helm.selectorLabels" . | nindent 8 }}
spec:
  containers:
    - name: {{.Values.imageSeatAdjusterApp.name}}
      image: "{{ .Values.imageSeatAdjusterApp.repository }}:{{ .Values.imageSeatAdjusterApp.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.imageSeatAdjusterApp.pullPolicy }}