---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^deploy/helm/templates/|^.sdv/k3d/helm/templates
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: >
            (?x)^(
                .*_pb2.py|
                .*_pb2.pyi|
                .*_pb2_grpc.py
            )$
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-unused-arguments


  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args: [
          "-rn",
          "-sn",
          "--rcfile=.pylintrc"
          ]
        types_or: [python]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args: [
          "--skip=B101"
          ]
        types_or: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.920"
    hooks:
      - id: mypy
        args: [src]
        language: system
        pass_filenames: false

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.0.9
    hooks:
      - id: helmlint
