apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.imageFeederCan.name}}
  labels:
    app: {{.Values.imageFeederCan.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.imageFeederCan.name}}
  template:
    metadata:
      labels:
        app: {{.Values.imageFeederCan.name}}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.imageFeederCan.daprAppid}}"
        dapr.io/log-level: "{{.Values.imageFeederCan.daprLogLevel}}"
        dapr.io/config: "config"
        dapr.io/app-protocol: "grpc"
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: feedercan
          image: {{.Values.imageFeederCan.repository}}:{{.Values.imageFeederCan.tag}}
          imagePullPolicy: {{.Values.imageFeederCan.pullPolicy}}
          env:
            - name: VEHICLEDATABROKER_DAPR_APP_ID
              value: {{.Values.imageVehicleDataBroker.daprAppid}}
            - name: LOG_LEVEL
              value: "info,databroker=info,dbcfeeder.broker_client=debug,dbcfeeder=debug"
            - name: CANDUMP_FILE
              value: "/data/candump"
          volumeMounts:
          - mountPath: "/data"
            name: pv-storage
